#!/bin/bash

## #custom
## Description: Import previously exported sql file into the project (.ddev/backup/db-dump.sql.gz)
## Usage: db-import
## Example: ddev db-import

ddev import-db --file="${DDEV_APPROOT}/.ddev/backup/db-dump.sql.gz"
ddev typo3 database:updateschema --no-interaction --quiet "table.add,field.add,*.change"
