services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SUNZINET\SzContentElements\:
    resource: '../Classes/*'

  SUNZINET\SzContentElements\Listener\Core\RegisterContentElementSqlDefinitions:
    tags:
      - name: event.listener
